name: terminal-external-command
channels:
  - conda-forge
dependencies:
  - nodejs=24
  - jupyter_server
  - jupyterlab
  - jupyterlite-terminal>=1.5.0
  - jupyterlite-core
  - jupyterlite-pyodide-kernel
